image: Visual Studio 2017

configuration:
#- Debug
- Release

artifacts:
- path: bin\$(configuration)\ShaderForm
  name: ShaderForm

install:
- ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex

before_build:
- nuget restore -Verbosity quiet
#- ps: Vsix-IncrementVsixVersion | Vsix-UpdateBuildVersion
#- ps: Vsix-TokenReplacement Tools\Zenseless.VSX\Source.extension.vsixmanifest 'Version = "([0-9\\.]+)"' 'Version = "{version}"'


build:
  publish_nuget: true             # package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: true     # generate and publish NuGet symbol packages
  include_nuget_references: true  # add -IncludeReferencedProjects option while packaging NuGet artifacts
  verbosity: minimal              # MSBuild verbosity level

after_test:
#- ps: Vsix-PushArtifacts | Vsix-PublishToGallery

deploy:
  release: ShaderForm-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: IGRhoLQi/yyC2ej7s79ZRU3PL3NScj4Kxh1Lyydg/CEvD/PbRwIilxmBziEHfwjJ
  artifact: ShaderForm
  draft: false
  prerelease: false
