version: 0.3.{build}

skip_tags: true # avoid deploy to GitHub loop 

image: Visual Studio 2017

configuration:
- Release

before_build:
- nuget restore -Verbosity quiet

build:
  project: All.sln
  publish_nuget: true             # package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: true     # generate and publish NuGet symbol packages
#  include_nuget_references: true  # add -IncludeReferencedProjects option while packaging NuGet artifacts
  verbosity: minimal              # MSBuild verbosity level

after_test:
- nuget pack _Common\Zenseless.nuspec -symbols -IncludeReferencedProjects -Properties version=%APPVEYOR_BUILD_VERSION%
- nuget pack _Common\Zenseless.Sources.nuspec -IncludeReferencedProjects -Properties version=%APPVEYOR_BUILD_VERSION%

artifacts:
- path: bin\$(configuration)\ShaderForm
  name: ShaderForm
- path: '*.nupkg'
  name: Zenseless
  
deploy:
- provider: GitHub
  release: ShaderForm-v$(appveyor_build_version)
  description: 'Auto generated by AppVeyor'
  auth_token:
    secure: IGRhoLQi/yyC2ej7s79ZRU3PL3NScj4Kxh1Lyydg/CEvD/PbRwIilxmBziEHfwjJ
  artifact: ShaderForm
  draft: false
  prerelease: true
  on:
    branch: master                # release from master branch only
    appveyor_repo_tag: true       # deploy on tag push only

- provider: NuGet
  api_key:
    secure: w5QCSXAxezmCE9sCYev5jEuL4uAicWaB5UrXtZkSMRfHVHr1nWyJnPaJO6r+rG5j
  skip_symbols: false
  artifact: Zenseless